# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: test
      shell: bash
      run: |
        
        if [[ -z $GITHUB_BASE_REF ]]; then
          echo "This is a PR to branch : "GITHUB_BASE_REF"
        fi

#        raw=$(git branch -r --contains ${{ github.ref }})
#        echo "raw: $raw"
#        echo "${{ github.event.base_ref }}"
#        echo "test : -> ${{ github.event.base_ref }}"
#        echo "test2 : -> $GITHUB_BASE_REF"
#        echo "BRANCH_NAME=$(echo $GITHUB_HEAD_REF)" >> $GITHUB_ENV
#        echo "BASE_BRANCH_NAME=$(echo $GITHUB_BASE_REF)" >> $GITHUB_ENV
#        echo "DOCKER_IMAGES_KEY=$(echo $GITHUB_RUN_ID)" >> $GITHUB_ENV

#    - name: Set up JDK 14
#      uses: actions/setup-java@v1
#      with:
#        java-version: 14
#    - name: Run JMH tests
#      run: gradle wrapper jmh
#
#    - uses: actions/upload-artifact@v2
#      with:
#        name: "jmh.json"
#        path: "*.txt"
